export const CHARACTERS = [
  {
    name: "Tom Cat",
    description: "Thomas \"Tom\" Cat is a fictional character and one of the two main protagonists in Metro-Goldwyn-Mayer's series of Tom and Jerry theatrical cartoon short films, created by William Hanna and Joseph Barbera. Tom is a blue/grey anthropomorphic domestic short-haired cat who first appeared in the 1940 animated short Puss Gets the Boot. Tom was originally known as \"Jasper\" during his debut in that short, however, beginning from his next appearance in The Midnight Snack and onwards, he is known as \"Tom\" or \"Thomas\"."
  },
  {
    name: "Jerry Mouse",
    description: "Jerry Mouse is a fictional character and one of the two main protagonists in Metro-Goldwyn Mayer's series of Tom and Jerry theatrical cartoon short films. Created by William Hanna and Joseph Barbera, Jerry is a brown house mouse, who first appeared as an unnamed mouse in the 1940 MGM animated short Puss Gets the Boot. Hanna gave the mouse's original name as \"Jinx\", while Barbera claimed the mouse went unnamed in his first appearance."
  },
  {
    name: "Spike Bulldog",
    description: "Spike has a grudge against Tom, not just because he's a cat, but because whenever they cross paths, Tom is interrupting quality time with his son, Tyke because he's too busy chasing Jerry to watch where he's going. Obviously, whenever Spike tells Tom not to do a certain thing (ex. dirty Tyke), Jerry overhears this and does his best to get Tom in trouble (in the example, Jerry would get Tyke as dirty as possible). Spike proceeds to beat Tom up thinking he was responsible for it. After Spike beats Tom, he is shown having a good time or resting peacefully with his son tyke and they are joined by Jerry their real saboteur, disturber and culprit who was really the one that Spike should beat up. Spike also appeared in some of the recent cartoons featuring a basset hound called Droopy, another popular MGM cartoon character."
  },
  {
    name: "Uncle Pecos",
    description: "Uncle Pecos is Jerry's cow-boyish uncle who appeared in the Tom and Jerry short \"Pecos Pest\", who wanted to stay with Jerry to visit. He is known to be always singing with a guitar, with a black cowboy hat that covers his eyes. He gets angry at Tom every time one of his guitar strings snap, because he plucks one whisker off of his face to replace it. He is voiced by Shug Fisher in Tom and Jerry and Scott McNeil in Tom and Jerry Tales."
  },
  {
    name: "Mammy Two Shoes",
    description: "Mammy Two Shoes (also known as Mammy, Mammy Two-Shoes, Mrs. Two Shoes in Tom and Jerry Tales or Dinah in the 1940 Tom and Jerry comics), is a recurring character in MGM's Tom and Jerry cartoons. She is a heavy-set, middle-aged African-American woman who often has to deal with the mayhem generated by the lead characters, but whether she is the owner of the home or merely the house-keeper is never really made clear. As a partially-seen character, she was famous for never showing her head and face (although it is briefly visible in Saturday Evening Puss and Part Time Pal). Mammy's appearances have often been edited out, dubbed, or re-animated as a slim white woman in later television showings, since her character is a mammy archetype now often regarded as racist. It was later revealed that her character was greatly inspired by Oscar-winning African-American actress and singer Hattie McDaniel, best known for playing \"Mammy\" in MGM and David O. Selznick's 1939 film."
  },
  {
    name: "Meathead Cat",
    description: "Meathead, also known as Frankie in Heavenly Puss, is a brown, mangy, generally dull-witted cat who first appeared in the Tom and Jerry 1943 short, Sufferin' Cats!, as Tom's rival. Meathead later reappeared in Baby Puss (in which he serves as one of three minor foes/a recurring villain) and additional shorts as one of Tom's alley cat buddies/foes."
  },
  {
    name: "Quacker",
    description: "Quacker Jeff Duck is a recurring character in the Tom and Jerry series. He is a yellow duck. Quacker is normally getting chased by Tom in the Tom and Jerry series and Jerry is trying to save Quacker from getting eaten by Tom. Another recurring character in the series was Little Quacker the duckling, who was later adapted into the Hanna-Barbera character Yakky Doodle. He appears in Little Quacker, Just Ducky, Downhearted Duckling, Southbound Duckling, That's My Mommy, Happy Go Ducky and The Vanishing Duck. Quacker talks a lot compared to Tom and Jerry. In many shorts, he is the only one who speaks. He's very trusting, even trusting Tom in many situations in which Tom wishes to eat him. He's a friend of Jerry, but unlike Jerry harbors no hard feelings towards Tom. Quacker is often mistaken as appearing in The Duck Doctor, but the Duck appearing in that short is a wild duck."
  },
  {
    name: "Lightning Cat",
    description: "Lightning is an orange cat who first appeared in the 1948 short Old Rockin' Chair Tom as Tom's rival. Lightning is named as such because in his first short, he practically moved at the speed of lightning. In later cartoons, Lightning often appeared as one of Tom's alley cat buddies/rivals. His last appearance is in Switchin' Kitten."
  }

]
